Added start date display in pre registration
FusionIIIT/Fusion pull request #1063
Opened 2023-02-07 14:54 UTC by Anunaya07

## Proposed changes:
Added start date display if it is set by the user.

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

2023-02-10 18:57 UTC, akshatnema requested changes
Remove the changes of requirements.txt. They are of previous versions.

2023-02-11 01:55 UTC, Aksh-Bansal-dev commented on FusionIIIT/applications/academic_procedures/views.py
> +        print("start_date: ", prd_start_date)
Remove this print statement.

2023-02-14 05:55 UTC, akshatnema approved these changes
Approved :heavy_check_mark:. Waiting for the review from @Aksh-Bansal-dev.

2023-02-14 06:48 UTC, Aksh-Bansal-dev approved these changes

2023-02-14 06:51 UTC, merged