(ac-4) : week 4 : fixed HOD leave module and some bugs in the student leave module.
FusionIIIT/Fusion pull request #1100
Opened 2023-02-12 17:27 UTC by Lawful2002

## Issue that this pull request solves

Closes: NA

## Proposed changes
Add try, except blocks to catch errors, along with default values for some of the models to prevent crashing if database contents are missing. Added some validation to the student leave module.

### Brief description of what is fixed or changed
HOD leave module now loads properly.
Extra validation is added to the student leave module.

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
No UI is changed

## Other information

Any other information that is important to this pull request

2023-02-16 17:48 UTC, Sahil-Rochlani reviewed
Approved @akshatnema

2023-02-16 19:11 UTC, akshatnema requested changes

2023-02-16 19:11 UTC, akshatnema commented on FusionIIIT/applications/leave/forms.py
> +        print(data.get('document').size)
kindly remove the `print` statement if not needed.

2023-02-16 19:11 UTC, akshatnema commented on requirements.txt
>  requests-oauthlib==1.3.0
Please don't change the requirements.txt

2023-02-16 19:11 UTC, akshatnema commented on FusionIIIT/applications/leave/models.py
> +    name = models.CharField(max_length=40, null=False, default='casual')
since you are changing the models.py, have you asked/informed these changes to Database Lead, Pranshu Nayak?

2023-02-22 17:13 UTC, Lawful2002 commented on requirements.txt
>  requests-oauthlib==1.3.0
fixed

2023-02-22 17:14 UTC, Lawful2002 commented on FusionIIIT/applications/leave/forms.py
> +        print(data.get('document').size)
removed

2023-02-23 10:08 UTC, akshatnema commented on requirements.txt
> +kombu
@Lawful2002 You have pushed the changes of `requirements.txt`, kindly remove these from the PR.

2023-03-03 14:40 UTC, Lawful2002 commented on requirements.txt
> +kombu
Fixed. PTAL

2023-03-03 14:42 UTC, Lawful2002 commented on FusionIIIT/applications/leave/models.py
> +    name = models.CharField(max_length=40, null=False, default='casual')
@pranshuNayak, PTAL. This change is required for making sure that the leave module doesn't fail completely when the database is incomplete. The value `casual` is being used as a fallback here.

2023-03-03 15:07 UTC, PranshuNayak commented on FusionIIIT/applications/leave/models.py
> +    name = models.CharField(max_length=40, null=False, default='casual')
LGTM!

2023-03-04 07:30 UTC, akshatnema approved these changes

2023-03-04 07:31 UTC, merged

2023-03-26 10:34 UTC, PranshuNayak commented
@Lawful2002 please push the migrations generated for the model changes.

2023-03-27 05:35 UTC, Lawful2002 commented
@PranshuNayak https://github.com/FusionIIIT/Fusion/pull/1186