workers would be assigned by SecIncharge instead of Caretaker
FusionIIIT/Fusion pull request #1132
Opened 2023-03-01 19:36 UTC by ujjawallele13

## Issue that this pull request solves

## Proposed changes
1. Workers would be now managed by section incharge assigned for the type of work.
2. Section Incharge would assign the worker to the complaint.

### Brief description of what is fixed or changed
1. DB changes :- Section incharge would now be linked to the workers
2. UI changes :-  Add/Delete and assign/reassign of workers by the section incharge
     
## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

Updated UI  for section incharge

![secIncharge assign worker](https://user-images.githubusercontent.com/111732396/222244740-67946ffa-456a-493c-8c50-00fabb1ce88f.png)

![secIncharge reassign worker](https://user-images.githubusercontent.com/111732396/222244810-dabdb9ad-7f5a-4c0e-b2d8-6e17b293e744.png)

![secIncharge manage workers](https://user-images.githubusercontent.com/111732396/222244880-65ddf6bc-6f14-4d38-9da5-8edf232e8830.png)

Below are the Updated UI  for caretaker

![caretaker update status](https://user-images.githubusercontent.com/111732396/222245025-270e8868-cb4c-4051-822f-28d16b457db9.png)

![caretaker mark as done](https://user-images.githubusercontent.com/111732396/222245078-10ded409-45c9-4ddb-91df-d73778985232.png)

## Other information

DB changes :- 
1. Added a new user "electricity_incharge" with password "user@123"

![incharge username](https://user-images.githubusercontent.com/111732396/222240270-17d4f165-5e9a-4d8f-baa5-eae211455204.png)

2. Added extra-info of "electricity_incharge" with id=2900 and user_type="staff"

![incharge extra info](https://user-images.githubusercontent.com/111732396/222240688-8327de77-b10a-4be0-8e9d-88865d115984.png)

3. Added "electricity_incharge" in section Incharge table
 
![electricity incharge entry](https://user-images.githubusercontent.com/111732396/222241088-040190df-5cb6-4f7d-899b-b9a9d96114f2.png)

4. Added worker for the "electricity_incharge"

![worker for incharge](https://user-images.githubusercontent.com/111732396/222241309-1fa91ff1-1a2b-4c3b-9992-b9d8987684d0.png)

2023-03-03 06:29 UTC, PranshuNayak reviewed
LGTM!

2023-03-03 06:37 UTC, PranshuNayak commented
@Aksh-Bansal-dev this PR has some DB changes, can u please see that they are properly migrated after merge?

2023-03-03 06:53 UTC, Arnav511 commented
I am getting the following error

![Screenshot (242)](https://user-images.githubusercontent.com/103359995/222650598-e662998d-0bb9-4320-869e-cc4c52cd5498.png)

Ping @ujjawallele13

2023-03-03 07:02 UTC, ujjawallele13 commented
> I am getting the following error
> 
> ![Screenshot (242)](https://user-images.githubusercontent.com/103359995/222650598-e662998d-0bb9-4320-869e-cc4c52cd5498.png)
> 
> Ping @ujjawallele13

You have to first migrate the changes which are done in the models of complaint_system @Arnav511

2023-03-03 07:17 UTC, Arnav511 commented
I have done that @ujjawallele13 
![Screenshot (243)](https://user-images.githubusercontent.com/103359995/222656016-3ee0baf5-58a2-4039-acfb-82f94565d554.png)

2023-03-03 07:21 UTC, samay-rgb commented
> I am getting the following error
> 
> ![Screenshot (242)](https://user-images.githubusercontent.com/103359995/222650598-e662998d-0bb9-4320-869e-cc4c52cd5498.png)
> 
> Ping @ujjawallele13



> I have done that @ujjawallele13 ![Screenshot (243)](https://user-images.githubusercontent.com/103359995/222656016-3ee0baf5-58a2-4039-acfb-82f94565d554.png)

You need to run migration commands whenever there is any db related change:

2023-03-03 07:26 UTC, samay-rgb commented on FusionIIIT/applications/complaint_system/views.py
> +        b = a.work_type
You can use better variable names instead of letters which will improve code readability.

2023-03-03 07:27 UTC, Arnav511 commented
I am still getting the same error.

2023-03-03 08:06 UTC, samay-rgb commented
@Arnav511 Check if this works for you

1. Revert model.py changes 
2. Run the migration commands
3. Apply model.py changes
4. Run the migration commands again

2023-03-03 14:30 UTC, ujjawallele13 commented
Are there any issues @samay-rgb @PranshuNayak @Arnav511 @akshatnema

2023-03-03 15:26 UTC, Arnav511 commented
I am still getting the same error of relation doesn't exist @ujjawallele13 @samay-rgb

2023-03-03 18:10 UTC, PranshuNayak commented
> Are there any issues @samay-rgb @PranshuNayak @Arnav511 @akshatnema

Your PR will be merged after some necessary changes have been completed in the docker file

2023-03-03 18:13 UTC, PranshuNayak commented
> I am still getting the same error of relation doesn't exist @ujjawallele13 @samay-rgb

have you reverted back to the initial database schemas, the one you forked while setup?

2023-03-03 19:42 UTC, Aksh-Bansal-dev commented
@ujjawallele13 Can you pull the latest changes from the main branch? It will be easier to check the migrations with docker.

2023-03-04 05:47 UTC, akshatnema commented
> @ujjawallele13 Can you pull the latest changes from the main branch? It will be easier to check the migrations with docker.

@ujjawallele13 Merge it with gad-3 only as I updated the upstream gad-3 branch with main.

2023-03-04 06:23 UTC, ujjawallele13 commented
Ok merged it. @Aksh-Bansal-dev @akshatnema

2023-03-04 06:38 UTC, akshatnema commented
@Arnav511 now please review the PR as this PR now have the latest changes with docker files.

2023-03-04 07:23 UTC, Aksh-Bansal-dev approved these changes
Migrations are working fine.

2023-03-05 09:07 UTC, ujjawallele13 commented
Could this PR be merged now @Arnav511 @akshatnema @PranshuNayak @samay-rgb

2023-03-05 09:16 UTC, samay-rgb approved these changes

2023-03-05 12:05 UTC, PranshuNayak commented
@akshatnema this pr can be merged

2023-03-05 12:18 UTC, akshatnema requested changes
Please remove the unnecessary comments from your changes.

2023-03-05 12:18 UTC, akshatnema commented on FusionIIIT/templates/complaintModule/complaint_secincharge_detail.html
> +            </a>-->
```suggestion
           
```

Please remove the comments from the PR if not needed.

2023-03-05 12:18 UTC, akshatnema commented on FusionIIIT/templates/complaintModule/complaint_secincharge_detail.html
> +                         </div> -->
```suggestion
  
```

2023-03-05 12:18 UTC, akshatnema commented on FusionIIIT/templates/complaintModule/complainthistory_secincharge.html
> +                    </th> -->
```suggestion
```

2023-03-05 12:18 UTC, akshatnema commented on FusionIIIT/templates/complaintModule/complainthistory_secincharge.html
> +
```suggestion
```

Don't add unnecessary spacing.

2023-03-05 12:18 UTC, akshatnema commented on FusionIIIT/templates/complaintModule/resolvecomplaint_caretaker.html
> +        </a> -->
```suggestion
```

2023-03-05 15:44 UTC, ujjawallele13 commented
Ok removed the unnecessary comments @akshatnema

2023-03-05 17:36 UTC, akshatnema approved these changes

2023-03-05 17:36 UTC, merged