RSPC Major changes, ready for deployment
FusionIIIT/Fusion pull request #1191
Opened 2023-03-27 10:30 UTC by Devendra072002

### Brief description of what is fixed or changed

- Added Check on the research procedures module that the faculty accessing has the designation 'Dean_RSPC' or not.
- If the logged-in user is not Dean RSPC then the faculty will be redirected to EIS
- Dean RSPC can view all the information about the research activities going on campus
- Dean RSPC can also view his personal profile using the view profile button
- Added user search form, so that faculty can search for information regarding research work going on the campus under particular faculty
- Added Generate citation functionality so that dean rspc can generate citations of projects under given faculty.
- Fixed generate report functionality, earlier the queries were not fetching correct data.
- Integrated faculty information using EIS module models.
## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

2023-03-27 11:32 UTC, ashray0124 commented
Approve @akshatnema 
Module name- RSPC (GAD-10)

2023-03-28 06:13 UTC, akshatnema requested changes
@Devendra072002 Kindly remove all the unnecessary commented code from the PR.

2023-03-28 06:13 UTC, akshatnema commented on FusionIIIT/applications/eis/api/views.py
> +    # return Response(data=resp, status=status.HTTP_200_OK)
```suggestion
    
```
Please remove unnecessary commented code.

2023-03-28 06:13 UTC, akshatnema commented on FusionIIIT/applications/research_procedures/views.py
> +    # all_user = User.objects.all()
```suggestion
```
same here

2023-03-28 06:13 UTC, akshatnema commented on FusionIIIT/applications/research_procedures/views.py
> +    #     fvisit.countryfull = countries[fvisit.country]
```suggestion
```

2023-03-28 10:00 UTC, Devendra072002 commented
@akshatnema I have done the changes as requested.

2023-03-29 08:32 UTC, akshatnema commented on FusionIIIT/templates/eisModulenew/rspc_generatereport.html
> +      //   })
Kindly remove this comment also.

2023-03-29 08:33 UTC, akshatnema commented on FusionIIIT/templates/rs/show_projects.html
> +        -->
Remove this comment too.

2023-03-29 08:34 UTC, akshatnema requested changes
Kindly remove all the unnecessary comments you have added to this PR.

2023-03-29 09:16 UTC, akshatnema approved these changes

2023-04-04 06:22 UTC, merged