PS-1 : Week 10 : Completed draft view page and endpoint for indent with mutiple items
FusionIIIT/Fusion pull request #1208
Opened 2023-04-04 18:54 UTC by kanha638

## Proposed changes

Created endpoint for viewing the details of drafted indent and added functionality to forward indent to some other person.

Created page that will eventually show all the details related to indent

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
<img width="1296" alt="Screenshot 2023-04-05 at 12 22 34 AM" src="https://user-images.githubusercontent.com/74721653/229891686-7183723a-75aa-4bc7-add8-82ac06eb7180.png">

<img width="1680" alt="Screenshot 2023-04-05 at 12 22 51 AM" src="https://user-images.githubusercontent.com/74721653/229891740-37fc80d3-ed32-4731-bc4d-caf07697a9aa.png">
<img width="1680" alt="Screenshot 2023-04-05 at 12 23 09 AM" src="https://user-images.githubusercontent.com/74721653/229891814-4201f86c-86ea-4622-90b6-ef17f00a6564.png">

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2023-04-04 18:55 UTC, kanha638 reviewed
Reviewed code

2023-04-04 19:02 UTC, kanha638 commented
Some more changes added now these functionality also included

1. delete drafted indents for indent with multiple items
2. view filled indent list
3. view filled ident details 
4. track filled indent status


Screenshots : 
<img width="1680" alt="Screenshot 2023-04-05 at 12 30 56 AM" src="https://user-images.githubusercontent.com/74721653/229893842-2dc3e520-97f5-4edb-a02e-2f4c79213b76.png">
<img width="1680" alt="Screenshot 2023-04-05 at 12 31 42 AM" src="https://user-images.githubusercontent.com/74721653/229894003-2fde48f4-8575-45fb-8d1f-1a12cea9ce08.png">
<img width="1680" alt="Screenshot 2023-04-05 at 12 31 55 AM" src="https://user-images.githubusercontent.com/74721653/229894044-33
<img width="959" alt="Screenshot 2023-04-05 at 12 32 10 AM" src="https://user-images.githubusercontent.com/74721653/229894099-196cb50e-31f2-42fe-80e9-b9d4b6361780.png">
02fd92-2a13-4b37-8c05-0ec695bb345f.png">

2023-04-04 19:29 UTC, harshp0702 reviewed
Approved. @akshatnema

2023-04-05 07:17 UTC, akshatnema commented on FusionIIIT/applications/ps1/views.py
> +# 	return render(request, 'ps1/createdindent.html', context)
Kindly remove this comment.

2023-04-05 07:19 UTC, akshatnema commented on FusionIIIT/templates/ps1/draftedIndentDetails.html
> +                        </div>-->
remove the comment.

2023-04-05 07:20 UTC, akshatnema commented on FusionIIIT/templates/ps1/draftedIndentDetails.html
> + -->
Remove this comment.

2023-04-05 07:20 UTC, akshatnema requested changes
Changes requested.

2023-04-05 07:28 UTC, kanha638 reviewed
@akshatnema changes done

2023-04-06 05:48 UTC, kanha638 commented
@akshatnema Please review the changes and merge it as we have to show its status on 214 server.

2023-04-06 17:56 UTC, akshatnema commented on FusionIIIT/templates/ps1/viewMyIndentFile.html
> + -->
```suggestion
```

2023-04-06 18:01 UTC, akshatnema requested changes

2023-04-06 18:01 UTC, akshatnema commented on FusionIIIT/applications/ps1/views.py
> +                        # 'holdsdesignations': holdsdesignations,
```suggestion
```

2023-04-06 18:01 UTC, akshatnema commented on FusionIIIT/applications/ps1/views.py
> +                        # 'holdsdesignations': holdsdesignations,
```suggestion
```

2023-04-06 18:01 UTC, akshatnema commented on FusionIIIT/applications/ps1/views.py
> +                # receive_design = receive_designation[0]
```suggestion
```

2023-04-06 18:01 UTC, akshatnema commented on FusionIIIT/applications/ps1/views.py
> +                # return HttpResponse ("success")
```suggestion
```

2023-04-06 18:01 UTC, akshatnema commented on FusionIIIT/templates/ps1/draftedIndentDetails.html
> +                                </div>-->
```suggestion
```

2023-04-06 18:01 UTC, akshatnema commented on FusionIIIT/templates/ps1/draftedIndentDetails.html
> +<!--                                    </div>-->
```suggestion
```

2023-04-07 19:08 UTC, kanha638 commented
@PranshuNayak , @samay-rgb Please Review changes on DB.

2023-04-07 19:28 UTC, harshp0702 reviewed
Approved. @akshatnema

2023-04-08 04:10 UTC, samay-rgb approved these changes

2023-04-08 05:18 UTC, PranshuNayak approved these changes
@akshatnema changes in models.py are fine.

2023-04-08 19:12 UTC, merged