add REST API for Vh module
FusionIIIT/Fusion pull request #1210
Opened 2023-04-05 11:05 UTC by Maveric-k07

## Issue that this pull request solves

Closes: #1209

## Proposed changes

### Add REST API for the Visitor Hostel module to allow the mobile app to make API calls to the application

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

No change in User Interface

## Other information

Any other information that is important to this pull request

2023-04-08 10:23 UTC, ashutosh-2002 commented
Approved @akshatnema

2023-04-08 19:43 UTC, akshatnema commented on FusionIIIT/applications/visitor_hostel/api/views.py
> +                   # 'occupied_rooms' : occupied_rooms,
Kindly remove these types of comments from the File Changes of PR.

2023-04-10 12:52 UTC, akshatnema requested changes

2023-04-10 12:52 UTC, akshatnema commented on FusionIIIT/applications/visitor_hostel/api/views.py
> +    #                                                                                                                   booking__booking_to__lte=date2, booking__status="Confirmed") | Q(booking__booki
```suggestion
```

2023-04-16 17:56 UTC, akshatnema commented
Kindly remove the same type of comments from this file FusionIIIT/applications/visitor_hostel/api/views.py

2023-04-18 18:42 UTC, merged