ac-3: Prof can submit Marks to assignment and made site responsive
FusionIIIT/Fusion pull request #1215
Opened 2023-04-06 11:15 UTC by tech-akash

## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2023-04-08 09:09 UTC, PranshuNayak commented
@tech-akash give the reference PR's where the changes visible in the migrations file of this PR are done.

2023-04-08 09:27 UTC, tech-akash commented
> @tech-akash give the reference PR's where the changes visible in the migrations file of this PR are done.

#1075 #1156

2023-04-08 09:52 UTC, PranshuNayak commented
@tech-akash the migrations files are ok. The PR containing the corresponding code changes in models.py i.e. #1156 needs to be merged first, but that PR should not contain any migration file, it should only contain the code changes. After that PR is merged without migrations file this PR can be merged.

2023-04-09 08:00 UTC, PranshuNayak approved these changes

2023-04-09 08:58 UTC, samay-rgb approved these changes

2023-04-10 08:38 UTC, akshatnema requested changes

2023-04-10 08:38 UTC, akshatnema commented on FusionIIIT/applications/online_cms/models.py
> +#                 self.feedback)
Remove this comment from the PR

2023-04-10 08:38 UTC, akshatnema commented on FusionIIIT/applications/online_cms/models.py
> +    # obj=Curriculum.objects.get(course_id=instance.course_id)
Same here

2023-04-10 08:38 UTC, akshatnema commented on FusionIIIT/applications/online_cms/views.py
> +            # doc=doc
```suggestion
```
Remove this comment

2023-04-10 08:58 UTC, akshatnema requested changes

2023-04-10 08:58 UTC, akshatnema commented on FusionIIIT/applications/online_cms/models.py
>      # media = models.FileField(upload_to=content_file_name, null=True, blank=True)
```suggestion
```

2023-04-10 08:58 UTC, akshatnema commented on FusionIIIT/applications/online_cms/models.py
> +    # obj=Curriculum.objects.get(course_id=instance.course_id)
```suggestion
```

2023-04-10 08:58 UTC, akshatnema commented on FusionIIIT/applications/online_cms/views.py
>              # print(videos)
```suggestion
```

2023-04-10 08:58 UTC, akshatnema commented on FusionIIIT/applications/online_cms/views.py
> +            # print("hii",sa)
```suggestion
```

2023-04-10 08:59 UTC, akshatnema approved these changes

2023-04-10 08:59 UTC, merged