AC-5: Integrate all new awards forms and update existing awards and their schemas
FusionIIIT/Fusion pull request #1230
Opened 2023-04-08 20:51 UTC by gaur-abhi524

## Proposed changes

All the previous forms for applying for convocation medals were changed and new models were made for every award with new and updated schema

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

2023-04-09 07:52 UTC, Abhishek-PratapSingh commented
Approve @akshatnema

2023-04-10 12:35 UTC, akshatnema requested changes
Remove these type of comments from the PR.

2023-04-10 12:35 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/forms/dandm_gold_medal.html
> +                <!-- </div> -->
remove this comment

2023-04-10 12:35 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/scholarships_student.html
> +</a>-->
Remove this comment

2023-04-10 12:35 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/scholarships_student.html
> +</div>-->
Remove this comment.

2023-04-10 12:49 UTC, akshatnema commented
Review required from @PranshuNayak and @samay-rgb.

2023-04-10 17:44 UTC, PranshuNayak reviewed
@gaur-abhi524 please remove indentation changes from models.py .

2023-04-10 17:58 UTC, gaur-abhi524 commented
@PranshuNayak can you mention the parts that need to be changed

2023-04-10 18:10 UTC, PranshuNayak commented
@gaur-abhi524 just make sure that the models which have been changes or added are only highlighted so that we can easily review.

2023-04-11 03:11 UTC, PranshuNayak reviewed
@gaur-abhi524 there are duplicate migrations in 0002 and 0003. Please push a single migration file for your changes , and don't modify the initial 0001

2023-04-11 04:12 UTC, PranshuNayak approved these changes
@gaur-abhi524 I have found 4 models migrations
newly created tables - DM_Proficiency_gold, IIITDM_Proficiency
modified tables - Director Gold, Director Silver

Since the file size is too large it's not possible to validate the migrations against each field, please cross-check at your end and verify.

Also only merging this PR will not create the database tables on 214 it needs to be deployed, so wait for some time if the table is not visible on 214.

2023-04-11 09:02 UTC, samay-rgb approved these changes

2023-04-11 09:15 UTC, akshatnema requested changes

2023-04-11 09:15 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/scholarships_student.html
> +</a>-->
```suggestion

```

2023-04-11 09:15 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/scholarships_student.html
> +</a>-->
```suggestion

```

2023-04-11 09:15 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/scholarships_student.html
> +{% comment %}The Publications about spacs  ends here!{% endcomment %}
```suggestion

```

2023-04-11 09:15 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/scholarships_student.html
> +</div>-->
```suggestion
```

2023-04-11 09:15 UTC, akshatnema commented on FusionIIIT/templates/scholarshipsModule/forms/dandm_gold_medal.html
> +                <!-- </div> -->
```suggestion
```

2023-04-11 09:18 UTC, akshatnema approved these changes

2023-04-11 09:18 UTC, merged