GAD1: added draft feature to announcement
FusionIIIT/Fusion pull request #1244
Opened 2023-04-14 17:53 UTC by CHOUHAN-MOHIT

- [x] added draft feature to announcement
- [x] fixed page not found error

2023-04-15 14:12 UTC, CHOUHAN-MOHIT commented
@akshatnema

2023-04-15 18:16 UTC, akshatnema commented
Require approval from reviewer.

2023-04-15 18:19 UTC, akshatnema commented
Review required from @PranshuNayak and @samay-rgb

2023-04-15 18:23 UTC, samay-rgb approved these changes

2023-04-15 19:16 UTC, PranshuNayak approved these changes
LGTM!

2023-04-16 08:51 UTC, CHOUHAN-MOHIT commented
@akshatnema added some more changes in department templates.

2023-04-16 17:38 UTC, akshatnema commented on FusionIIIT/applications/department/views.py
> +        # print("is_draft:" , is_draft)
```suggestion
```

2023-04-16 17:39 UTC, akshatnema commented on FusionIIIT/applications/department/views.py
> +        # department_notif(usrnm, recipients , message)
```suggestion
```

2023-04-16 17:39 UTC, akshatnema commented on FusionIIIT/templates/department/edit-draft.html
> +        // console.log("success");
```suggestion
```

2023-04-16 17:40 UTC, akshatnema commented on FusionIIIT/templates/department/edit-draft.html
> +        // console.log(document.getElementById("btn-publish-dft").getAttribute("data-id"));
```suggestion
```

2023-04-16 17:40 UTC, akshatnema commented on FusionIIIT/templates/department/edit-draft.html
> +        // console.log(allFields);
```suggestion
```

2023-04-16 17:41 UTC, akshatnema requested changes

2023-04-16 17:41 UTC, akshatnema commented on FusionIIIT/templates/department/sm_dep.html
> +                    </span> {% endcomment %}
If you are making this part of code as comment, kindly remove the code and don't make it as comment.

2023-04-17 06:07 UTC, akshatnema approved these changes

2023-04-17 06:08 UTC, merged