Medicine
FusionIIIT/Fusion pull request #1253
Opened 2023-04-16 14:09 UTC by divyanshkhetan

## Proposed changes
- Fixed stock system
- Fixed doctor's model

## Types of changes

_Put an `x` in the boxes that apply_

-   [x] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
![image](https://user-images.githubusercontent.com/68158825/232318130-1c233d07-610a-4be1-882e-2d3b5925e3f3.png)

2023-04-16 14:12 UTC, divyanshkhetan commented
@akshatnema please look into this.

2023-04-16 14:38 UTC, NuthanReddy646 commented
Approve @akshatnema

2023-04-16 17:53 UTC, akshatnema reviewed
Review required from @PranshuNayak and @samay-rgb

2023-04-17 05:00 UTC, PranshuNayak requested changes
Please make sure to do all necessary changes at once while changing the model schema. In the previous PR, you added contact_no now you are removing it.

2023-04-17 05:00 UTC, PranshuNayak commented on FusionIIIT/applications/health_center/models.py
>      def __str__(self):
The field names need not be prefixed with hospital, address, and phone are self-explanatory, no need to use hospital_address and hospital_phone. Change hospital_name to name too.

2023-04-17 05:25 UTC, PranshuNayak approved these changes

2023-04-17 05:31 UTC, samay-rgb approved these changes

2023-04-17 05:59 UTC, merged