HR Module: CPDA and LTC forms implemented
FusionIIIT/Fusion pull request #1318
Opened 2024-03-08 19:29 UTC by Akshay-Pahuja

## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes
- no issues present 
- made from scratch

## Brief description of what is fixed or changed

### New Features implemented
- LTC form implemented : submission, view,  hr can see requests, hod see requests, file getting forwarded, director view requests,
- CPDA form implemented : submission , view, hr can see requests, hod see requests, file getting forwarded, director view requests,

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

2024-03-08 19:31 UTC, Akshay-Pahuja commented
Maintainers to be tagged :
@prajjwalkapoor

2024-03-10 13:24 UTC, prajjwalkapoor requested changes
Hey @Akshay-Pahuja, LGTM.  Just do this minor change commit it on the same branch.

2024-03-10 13:24 UTC, prajjwalkapoor commented on FusionIIIT/templates/hr2Module/view_cpda_form_hrAdmin.html
> +<!-- {% extends 'globals/base.html' %}
If we don't need these files then instead of commenting, let's remove them.

2024-03-10 13:24 UTC, prajjwalkapoor commented on FusionIIIT/templates/hr2Module/view_cpda_request_hr.html
> +<!-- <div class="content">
same here, we can remove this.

2024-03-10 13:32 UTC, prajjwalkapoor commented
Also @Akshay-Pahuja, we need a walkthrough video of your changes.

2024-04-21 18:25 UTC, closed without merging