Latest Updated Commit on 10th march
FusionIIIT/Fusion pull request #1320
Opened 2024-03-10 16:29 UTC by Harshan-Nayak

## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2024-03-10 18:38 UTC, varun7singh commented
Hey @Harshan-Nayak please add a demo video and explain the code changes

2024-03-10 18:42 UTC, varun7singh reviewed
Please remove the migration files

2024-03-10 18:50 UTC, varun7singh requested changes
Please remove the migration files

2024-03-11 11:16 UTC, Harshan-Nayak commented
https://github.com/FusionIIIT/Fusion/assets/128978924/ed2c9646-93bc-4e60-8422-5ec32586637b

This is code change video

2024-03-11 11:26 UTC, Harshan-Nayak commented
Removed Migration files

2024-03-11 11:31 UTC, varun7singh requested changes
There are still some migration files

2024-03-11 11:35 UTC, VarunGitGood commented on FusionIIIT/applications/globals/migrations/0008_auto_20240217_2112.py
we do not need these migration files

2024-03-11 11:35 UTC, VarunGitGood commented on fusionlab_backup_New.sql
Was this asked to be pushed by the database team? @Kushagra-Yadav

2024-03-11 11:40 UTC, Harshan-Nayak commented
Also Removed Migration files from globals

2024-03-11 11:52 UTC, varun7singh commented
@priyansh61 do we not need global migrations as well?

2024-03-11 11:52 UTC, varun7singh commented
@Harshan-Nayak everything else looks good let me just confirm this.

2024-03-17 18:56 UTC, merged