Os 2
FusionIIIT/Fusion pull request #1346
Opened 2024-03-18 15:27 UTC by prem-charan

## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

### Brief description of what is fixed or changed
added announcement functionality and also added doctors and pathologist schedule
fixed bugs in code
resolved api issues

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2024-03-18 15:30 UTC, prem-charan commented
@ChaudharyRaman @varun7singh @prajjwalkapoor

2024-03-18 17:58 UTC, varun7singh requested changes
remove this

2024-03-18 17:58 UTC, varun7singh commented on FusionIIIT/applications/scholarships/migrations/0002_auto_20240218_0103.py
> +
remove these migrations

2024-03-18 19:58 UTC, prem-charan commented
Demo Video link :
https://drive.google.com/file/d/16mVkWS9FiwSLyKdKvuR5vg7MWTIcdrIw/view?usp=drive_link

2024-03-19 07:05 UTC, prem-charan commented
@varun7singh migrations removed

2024-03-19 08:45 UTC, varun7singh requested changes

2024-03-19 08:45 UTC, varun7singh commented on FusionIIIT/applications/programme_curriculum/migrations/0002_auto_20240218_0103.py
> +from django.db import migrations, models
Remove this file

2024-03-19 11:05 UTC, prem-charan commented
@varun7singh file removed

2024-03-19 11:36 UTC, varun7singh commented
LGTM

2024-03-19 11:36 UTC, merged