CPDA form ,leave form,Appraisal form created
FusionIIIT/Fusion pull request #1441
Opened 2024-04-11 20:39 UTC by 21BCS035

## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

    1)no issues present

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [x] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [x] I have performed a self-review of my own code
-   [x] I have created new branch for this pull request
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] My changes does not break the current system and it passes all the current test cases.

2024-04-11 20:41 UTC, 21BCS035 commented
@ChaudharyRaman required task has been done.

2024-04-11 20:50 UTC, 21BCS035 commented
@ChaudharyRaman please also update the sheet after merging the PR asap

2024-04-14 14:27 UTC, Priyansh61 commented
@21BCS035  Please update the PR description with a screencast of the working of the module? Helps us review the PR a bit quick.

2024-04-14 15:03 UTC, theoden42 reviewed
Please handle the necessary changes and remove the comments, its very hard to read the code with them.

2024-04-14 15:03 UTC, theoden42 commented on FusionIIIT/applications/hr2/views.py
> +def get_current_file_owner(file_id: int) -> User:
Why is this function repeated here? It can be imported from the filetracking sdk methods.

2024-04-14 15:03 UTC, theoden42 commented on FusionIIIT/applications/hr2/views.py
> +        print(request.POST.get('context'))
Please remove the unnecessary print statements, makes the code harder to read.

2024-04-14 15:03 UTC, theoden42 commented on FusionIIIT/applications/hr2/views.py
> +        if(action == '0'):
More descriptive values can be used here to describe actions.

2024-04-14 18:38 UTC, theoden42 commented on FusionIIIT/applications/hr2/views.py
> +from applications.filetracking.models import Tracking
avoid working directly with FileTracking models and use sdk methods in stead

2024-04-14 18:46 UTC, theoden42 requested changes
Please make the necessary changes and provide a video demo for the working of the system.

2024-04-14 18:46 UTC, theoden42 commented on FusionIIIT/applications/hr2/views.py
> +        action = form_data2.get('action')
If it's hard to provide descriptive values to the actions, please provide comments regarding which value maps to which action.

2024-04-20 14:06 UTC, merged