Latest Updated Code with Dashboard
FusionIIIT/Fusion pull request #1453
Opened 2024-04-14 14:12 UTC by harshabonu

## Issue that this pull request solves

Closes: # (issue number)

## Proposed changes

### Brief description of what is fixed or changed

## Types of changes

_Put an `x` in the boxes that apply_

-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Other (please describe):

## Checklist

_Put an `x` in the boxes that apply_

-   [ ] My code follows the [style guidelines of this project](https://docs.google.com/document/d/1GI2Hile8UbGZ82gFe1y4wAVPcNPXip1cmXTzog1S41U/edit)
-   [ ] I have performed a self-review of my own code
-   [ ] I have created new branch for this pull request
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

2024-04-14 19:34 UTC, Priyansh61 commented
@harshabonu Kindly completely fill the PR template, helps us understand the PR scope and review faster

2024-04-15 10:26 UTC, harshabonu commented
> @harshabonu Kindly completely fill the PR template, helps us understand the PR scope and review faster

Kindly, Re-Check the pull request

2024-04-17 13:40 UTC, Priyansh61 commented
@ChaudharyRaman is reviewing the PR.

2024-04-17 15:27 UTC, ChaudharyRaman requested changes
@harshabonu Please remove all the migrations files manually and push.
 Otherwise LGTM @Priyansh61 can be merged.

2024-04-17 15:27 UTC, ChaudharyRaman commented on FusionIIIT/applications/examination/api/views.py
> +#Login
Why so much commented code, Can be removed if not necessary.

2024-04-17 17:03 UTC, Priyansh61 commented
@ChaudharyRaman Is thie functionality working properly? And are there any breaking changes which the module causes to the others?

2024-04-17 18:55 UTC, harshabonu commented
@ChaudharyRaman @Priyansh61 
Migration Files are removed and required changes are made.
Kindly, Once again re-check the PR.

2024-04-17 21:30 UTC, merged