Optimized EIS Module Queries
FusionIIIT/Fusion pull request #287
Opened 2021-03-12 05:20 UTC by ankits2206-github

2021-03-12 13:21 UTC, dynamoh requested changes

2021-03-12 13:21 UTC, dynamoh commented on FusionIIIT/applications/eis/views.py
> +        pass
Throw proper errors - Use loggers

2021-03-12 17:29 UTC, ankits2206-github commented on FusionIIIT/applications/eis/views.py
> +        pass
Done .

2021-03-12 18:45 UTC, adi0311 requested changes
Remove these print statements:-
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L421
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L427
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L462
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L482
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L521
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L534
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L568
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L651
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L677
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L742
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L801
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L816
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L844
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L871
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L1029
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L1047
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L1048
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L1059
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L1130
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L1135

2021-03-12 18:49 UTC, adi0311 requested changes
Optimize the import by merging these lines:-
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L17
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L19
https://github.com/FusionIIIT/Fusion/blob/960ef69f778aab5c1fd2f33fee7687cfc14862a5/FusionIIIT/applications/eis/views.py#L20

2021-03-14 07:26 UTC, dynamoh approved these changes

2021-03-14 07:27 UTC, merged