Optimising office_module,online_cms,notification modules ..
FusionIIIT/Fusion pull request #300
Opened 2021-03-15 00:43 UTC by muditripathi

2021-03-22 07:27 UTC, dynamoh requested changes

2021-03-22 07:27 UTC, dynamoh commented on FusionIIIT/applications/office_module/views.py
> +    current_hold_design = HoldsDesignation.objects.select_related('user','designation','working').filter(user=User.objects.all().first()).get(designation=current_design)
```User.objects.all().first()``` don't hardcode this
filter for the logged in user.

2021-03-23 17:02 UTC, mohit00482 commented on FusionIIIT/applications/office_module/views.py
> +        sent_hold_design = HoldsDesignation.select_related('user','designation','working').objects.get(designation=sent_design)
Here it will throw an error, make sure it is working.

2021-03-23 17:42 UTC, mohit00482 commented on FusionIIIT/applications/office_module/views.py
> +        sent_hold_design = HoldsDesignation.objects.select_related('user','designation','working').get(designation=sent_design)
Looks fine now

2021-03-24 03:15 UTC, dynamoh approved these changes

2021-03-24 03:16 UTC, merged