HR2 module
FusionIIIT/Fusion pull request #303
Opened 2021-03-15 11:08 UTC by pranavelric

Employee models and basic UI created for HR2 module

2021-03-15 12:51 UTC, pranavelric commented
added database model in application/hr2/models.py

2021-03-15 16:02 UTC, adi0311 requested changes

2021-03-15 16:02 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +def employee(models.Model):
This should be a class. Class name should be in PascalCase.

2021-03-15 16:02 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    id = models.OneToOneField(ExtraInfo, on_delete=models.CASCADE, primary_key=True)
Change the name of this field.

2021-03-15 16:02 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    gender = models.CharField(max_length=1, choices=Constants.GENDER_CHOICES)
Redundant field, already present in ExtraInfo.

2021-03-15 16:02 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    blood_group =  models.CharField(max_length=40, default='')
Provide Choices.

2021-03-15 16:04 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    blood_group =  models.CharField(max_length=40, default='')
Change all the models from functions to class(change their naming convention from snake_case to PascalCase), remove all the redundant fields and provide choices where possible.

2021-03-15 16:37 UTC, adi0311 requested changes

2021-03-15 16:37 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    first_name = models.CharField(max_length=40, default='')
Already present in default User model of Django.

2021-03-15 16:37 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    last_name = models.CharField(max_length=40, default='')
This also.

2021-03-15 16:37 UTC, adi0311 commented on FusionIIIT/Fusion/urls.py
> +    # new
Remove this line.

2021-03-15 16:37 UTC, adi0311 commented on FusionIIIT/applications/globals/models.py
> +
Don't add extra spaces for no reason.

2021-03-24 10:49 UTC, adi0311 commented on FusionIIIT/applications/hr2/models.py
> +    user = models.OneToOneField(User, on_delete=models.CASCADE)
User is already present in ExtraInfo. Remove it as it is redundant.
Docstrings still not added. Add docstring to every models and views.

2021-03-24 10:50 UTC, adi0311 commented on FusionIIIT/applications/hr2/views.py
> +def hrAdmin(request):
You are instructed to read PEP-8 and follow those guidelines.

2021-04-05 10:49 UTC, Palash1999 commented
This PR is not maintained anymore, please refer to this new pull request of HR-2 Module [here](https://github.com/FusionIIIT/Fusion/pull/357).

2021-05-11 12:53 UTC, closed without merging