AD-1(department module)
FusionIIIT/Fusion pull request #306
Opened 2021-03-15 11:36 UTC by gshubha

In this module for students as a user, we have created the UI that shows the working of different departments and various other functionalities like filing complaints about a particular department and other things. A pdf of required work and screenshots of UI are in the folder(\applications\department\UI and details)

2021-03-18 09:22 UTC, hvsblogger commented on FusionIIIT/applications/department/models.py
> +
special request table is not present as mentioned in DB Schema

2021-03-30 09:10 UTC, adi0311 commented on FusionIIIT/Fusion/settings/development.py
> +        'HOST': 'localhost',
Please don't commit or push this file. Remove it from the staging area before making any commit.

2021-03-30 09:12 UTC, adi0311 commented on FusionIIIT/applications/central_mess/migrations/0018_merge_20210303_2016.py
> +from django.db import migrations
Don't push migrations. It is already told to not to do this. If you are using local DB, just simply remove these files from the staging area before commit.

2021-03-30 09:21 UTC, adi0311 requested changes

2021-03-30 09:21 UTC, adi0311 commented on FusionIIIT/applications/department/urls.py
> +<<<<<<< HEAD
Don't push the code that can break the application. Resolve the conflicts properly. VS Code has an excellent feature to resolve conflict. Make sure you do this before committing your code.

2021-03-30 09:21 UTC, adi0311 commented on FusionIIIT/applications/department/views.py
> +    print(request.user)
Remember final code should not have any print statements or unnecessary comments. Use loggers(that too when there might be some errors, for example with try-except).

2021-03-30 09:21 UTC, adi0311 commented on FusionIIIT/applications/department/views.py
> +def BtechFirstYear_Students(request):
Please, it's been told several times to follow PEP-8. If you couldn't find that doc, here is the [link](https://www.python.org/dev/peps/pep-0008/)
Also, to summarize for you, take care of these points:-

- Make sure each view function and model class should have a docstring.
- Class name is in PascalCase.
- Functions, variables name should be in snake_case.

2021-04-06 04:57 UTC, closed without merging