HR1 module update
FusionIIIT/Fusion pull request #307
Opened 2021-03-15 11:46 UTC by ajtheb

Appraisal models added

2021-03-16 05:32 UTC, adi0311 requested changes

2021-03-16 05:32 UTC, adi0311 commented on FusionIIIT/applications/establishment/models.py
> +class courses_instructed(models.Model):
Class name should be in Pascal Case.

2021-03-16 05:32 UTC, adi0311 commented on FusionIIIT/applications/establishment/models.py
> +class Appraisal(models.Model):
Add docstring to every model's class.

2021-03-16 05:32 UTC, adi0311 commented on FusionIIIT/applications/establishment/models.py
> +    UGorPG=models.CharField(max_length=2,blank=True, null=True)
Fields name should be in snake case.

2021-03-16 09:30 UTC, ajtheb commented on FusionIIIT/applications/establishment/models.py
> +class courses_instructed(models.Model):
Please check now.

2021-03-22 09:48 UTC, merged

2021-03-22 15:17 UTC, ajtheb commented on FusionIIIT/applications/establishment/models.py
> +    UGorPG=models.CharField(max_length=2,blank=True, null=True)
please check now