Refactoring1
FusionIIIT/Fusion pull request #777
Opened 2022-03-10 10:38 UTC by 2019051

Code refactoring for urls and views

2022-03-10 10:39 UTC, 2019051 commented
@anurag0singh

2022-04-28 09:19 UTC, MananJethwani commented
@anurag0singh kindly review this PR ASAP

2022-04-29 07:25 UTC, anurag0singh requested changes
@2019051 This PR has conflicts, please resolve them.

2022-04-29 23:35 UTC, anurag0singh commented
Closing this PR as discussed.

2022-04-29 23:35 UTC, closed without merging